name: dinengros

version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+11
  get: ^3.26.0
  dio: ^3.0.4
  google_fonts: ^1.1.2
  flutter_spinkit: ^4.1.2+1
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.3
  flutter_local_notifications: ^4.0.1
  search_choices: ^1.0.17
  dropdown_search: ^0.4.9
  fluttertoast: ^7.1.6
  font_awesome_flutter: ^8.12.0
  url_launcher: ^5.7.10
  device_preview:
  audioplayers: ^0.16.2
  flutter_screenutil: ^4.0.3
  progress_dialog: ^1.2.4
  flutter_typeahead: ^2.0.0
  flutter_svg: ^0.18.0
  package_info: ^0.4.3+4


dev_dependencies:
  flutter_test:
    sdk: flutter 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/sounds/